export const DarkTheme = {
  PRIMARY_BACKGROUND: "#000000ff",
  PRIMARY_BACKGROUND_WHITE: "#f7f1f1ff",
  PRIMARY_TEXT: "#e8e9ebff",
  PRIMARY_TEXT_BLACK: "#000000ff",
  PRIMARY_TEXT_WHITE: "#ffffff",
  PRIMARY_BORDER: "#cacdd3ff",
  PRIMARY_BORDER_DARK: "#3a3f47",
  PRIMARY_ACTIVE_BUTTON: "#2a2f37",
  PRIMARY_INACTIVE_BUTTON: "#2a2f37",
  PRIMARY_ACTIVE_BUTTON_TEXT: "#f7f8faff",
  SECONDARY_BACKGROUND: "#131519",
  CHECKBOX_SUCCESS: "#4ECDC4",
  CHECKBOX_DARK: "#2B9E96", // Darker Teal for checked state
  CHECKBOX_SUCCESS_ACTIVE: "#e5e8ecff",
  CHECKBOX_INACTIVE: "#e8e9ebff",
  PLACEHOLDER: "#cacdd39a",
  ERROR_INPUT_TEXT: "#d16b43ff",
};

export const LightTheme = {
  PRIMARY_BACKGROUND: "#FFFFFF",
  PRIMARY_BACKGROUND_WHITE: "#000000",
  PRIMARY_TEXT: "#1A1A1A",
  PRIMARY_TEXT_BLACK: "#FFFFFF",
  PRIMARY_TEXT_WHITE: "#000000",
  PRIMARY_BORDER: "#E0E0E0",
  PRIMARY_BORDER_DARK: "#D1D1D1",
  PRIMARY_ACTIVE_BUTTON: "#007AFF", // Blue for active actions
  PRIMARY_INACTIVE_BUTTON: "#F0F0F0",
  PRIMARY_ACTIVE_BUTTON_TEXT: "#FFFFFF",
  SECONDARY_BACKGROUND: "#F8F9FA",
  CHECKBOX_SUCCESS: "#4ECDC4",
  CHECKBOX_DARK: "#2B9E96",
  CHECKBOX_SUCCESS_ACTIVE: "#3AAFA9",
  CHECKBOX_INACTIVE: "#CCCCCC",
  PLACEHOLDER: "#999999",
  ERROR_INPUT_TEXT: "#FF3B30",
};

// Default to DarkTheme for backward compatibility if needed, but components should use useTheme
export const COLORS = DarkTheme;
